"""Majora's Mask item icons -> the game's own get-item models (display lists), view angles.

icon texture name: (display lists, yaw, pitch, roll[, prim, env])
Colour display lists (…ColorDL) come before the geometry they colour, as the draw code does.
"""
G = "objects/object_gi_"
FACE = (0, 0, 0)          # masks: straight on
TILT = (25, 15, 0)        # most items: a little from the side and above


def _v(dls, ang=TILT):
    return (dls,) + tuple(ang)


def _bottle(*dls):
    return _v(list(dls), (15, 10, 0))


ICONS = {
    # ---- items
    "gItemIconBombTex": _v([G + "bomb_1/gGiBombDL"]),
    "gItemIconBombchuTex": _v([G + "bomb_2/gGiBombchuDL"], (40, 20, 0)),
    "gItemIconDekuNutTex": _v([G + "nuts/gGiNutDL"]),
    "gItemIconDekuStickTex": _v([G + "stick/gGiStickDL"], (0, 0, -40)),
    "gItemIconMagicBeansTex": _v([G + "bean/gGiBeanDL"]),
    "gItemIconPowderKegTex": _v([G + "bigbomb/gGiPowderKegBarrelDL", G + "bigbomb/gGiPowderKegGoronSkullAndFuseDL"]),
    "gItemIconPictographBoxTex": _v([G + "camera/gGiPictoBoxBodyAndLensDL", G + "camera/gGiPictoBoxFrameDL"]),
    "gItemIconLensofTruthTex": _v([G + "glasses/gGiLensDL", G + "glasses/gGiLensGlassDL"]),
    "gItemIconHookshotTex": _v([G + "hookshot/gGiHookshotDL"], (60, 10, -30)),
    "gItemIconBowTex": _v([G + "bow/gGiBowHandleDL", G + "bow/gGiBowStringDL"], (0, 0, 0)),
    "gItemIconFireArrowTex": _v([G + "m_arrow/gGiMagicArrowFireColorDL", G + "m_arrow/gGiMagicArrowAmmoDL"], (0, 0, -45)),
    "gItemIconIceArrowTex": _v([G + "m_arrow/gGiMagicArrowIceColorDL", G + "m_arrow/gGiMagicArrowAmmoDL"], (0, 0, -45)),
    "gItemIconLightArrowTex": _v([G + "m_arrow/gGiMagicArrowLightColorDL", G + "m_arrow/gGiMagicArrowAmmoDL"], (0, 0, -45)),
    "gItemIconBowFireTex": _v([G + "bow/gGiBowHandleDL", G + "bow/gGiBowStringDL", G + "m_arrow/gGiMagicArrowFireColorDL", G + "m_arrow/gGiMagicArrowAmmoDL"], (0, 0, 0)),
    "gItemIconBowIceTex": _v([G + "bow/gGiBowHandleDL", G + "bow/gGiBowStringDL", G + "m_arrow/gGiMagicArrowIceColorDL", G + "m_arrow/gGiMagicArrowAmmoDL"], (0, 0, 0)),
    "gItemIconBowLightTex": _v([G + "bow/gGiBowHandleDL", G + "bow/gGiBowStringDL", G + "m_arrow/gGiMagicArrowLightColorDL", G + "m_arrow/gGiMagicArrowAmmoDL"], (0, 0, 0)),
    "gItemIconOcarinaOfTimeTex": _v([G + "ocarina/gGiOcarinaOfTimeDL", G + "ocarina/gGiOcarinaOfTimeHolesDL"], (30, 30, 0)),
    "gItemIconSongNoteTex": _v([G + "melody/gGiSongNoteDL"], (0, 0, 0)),
    "gItemIconBombersNotebookTex": _v([G + "schedule/gGiBombersNotebookDL"], (0, 20, 0)),
    "gItemIconTingleMapTex": _v([G + "fieldmap/gGiTingleMapDL"], (0, 30, 0)),
    "gItemIconRoomKeyTex": _v([G + "reserve_b_00/gGiRoomKeyDL"]),
    "gItemIconLetterToMamaTex": _v([G + "reserve_b_01/gGiLetterToMamaEnvelopeLetterDL", G + "reserve_b_01/gGiLetterToMamaInscriptionsDL"], (0, 30, 0)),
    "gItemIconLetterToKafeiTex": _v([G + "reserve_c_00/gGiLetterToKafeiEnvelopeLetterDL", G + "reserve_c_00/gGiLetterToKafeiInscriptionsDL"], (0, 30, 0)),
    "gItemIconPendantOfMemoriesTex": _v([G + "reserve_c_01/gGiPendantOfMemoriesDL"]),
    "gItemIconMoonsTearTex": _v([G + "reserve00/gGiMoonsTearItemDL"]),
    "gItemIconLandDeedTex": _v([G + "reserve01/gGiTitleDeedLandColorDL", G + "reserve01/gGiTitleDeedPaperDL", G + "reserve01/gGiTitleDeedSealAndRibbonDL"], (0, 30, 0)),
    "gItemIconSwampDeedTex": _v([G + "reserve01/gGiTitleDeedSwampColorDL", G + "reserve01/gGiTitleDeedPaperDL", G + "reserve01/gGiTitleDeedSealAndRibbonDL"], (0, 30, 0)),
    "gItemIconMountainDeedTex": _v([G + "reserve01/gGiTitleDeedMountainColorDL", G + "reserve01/gGiTitleDeedPaperDL", G + "reserve01/gGiTitleDeedSealAndRibbonDL"], (0, 30, 0)),
    "gItemIconOceanDeedTex": _v([G + "reserve01/gGiTitleDeedOceanColorDL", G + "reserve01/gGiTitleDeedPaperDL", G + "reserve01/gGiTitleDeedSealAndRibbonDL"], (0, 30, 0)),
    # ---- bottles
    "gItemIconEmptyBottleTex": _bottle(G + "bottle/gGiEmptyBottleGlassDL", G + "bottle/gGiEmptyBottleCorkDL"),
    "gItemIconEmptyBottle2Tex": _bottle(G + "bottle/gGiEmptyBottleGlassDL", G + "bottle/gGiEmptyBottleCorkDL"),
    "gItemIconRedPotionTex": _bottle(G + "bottle_red/gGiRedPotionBottleDL"),
    "gItemIconGreenPotionTex": _bottle(G + "liquid/gGiPotionContainerGreenPotColorDL", G + "liquid/gGiPotionContainerPotDL",
                                       G + "liquid/gGiPotionContainerGreenLiquidColorDL", G + "liquid/gGiPotionContainerLiquidDL",
                                       G + "liquid/gGiPotionContainerGreenPatternColorDL", G + "liquid/gGiPotionContainerPatternDL"),
    "gItemIconBluePotionTex": _bottle(G + "liquid/gGiPotionContainerBluePotColorDL", G + "liquid/gGiPotionContainerPotDL",
                                      G + "liquid/gGiPotionContainerBlueLiquidColorDL", G + "liquid/gGiPotionContainerLiquidDL",
                                      G + "liquid/gGiPotionContainerBluePatternColorDL", G + "liquid/gGiPotionContainerPatternDL"),
    "gItemIconBottledFairyTex": _bottle(G + "bottle_04/gGiFairyBottleContentsDL", G + "bottle_04/gGiFairyBottleGlassCorkDL"),
    "gItemIconBottledZoraEggTex": _bottle(G + "bottle_15/gGiZoraEggBottleContentsDL", G + "bottle_15/gGiZoraEggBottleGlassAndCorkDL"),
    "gItemIconBottledSeahorseTex": _bottle(G + "seahorse/gGiSeahorseBodyDL", G + "bottle_16/gGiSeahorseBottleGlassAndCorkDL"),
    "gItemIconChateauRomaniTex": _bottle(G + "bottle_21/gGiChateauRomaniBottleDL"),
    "gItemIconBottledHylianLoachTex": _bottle(G + "bottle_22/gGiHylianLoachBottleContentsDL", G + "bottle_22/gGiHylianLoachBottleGlassCorkWaterDL"),
    "gItemIconBottledFullMilkTex": _bottle(G + "milk/gGiMilkBottleContentsDL", G + "milk/gGiMilkBottleGlassDL"),
    "gItemIconBottledHalfMilkTex": _bottle(G + "milk/gGiMilkBottleContentsDL", G + "milk/gGiMilkBottleGlassDL"),
    "gItemIconBottledPoeTex": _bottle(G + "ghost/gGiPoeContainerPoeColorDL", G + "ghost/gGiPoeContainerLidDL",
                                      G + "ghost/gGiPoeContainerGlassDL", G + "ghost/gGiPoeContainerContentsDL"),
    "gItemIconBottledBigPoeTex": _bottle(G + "ghost/gGiPoeContainerBigPoeColorDL", G + "ghost/gGiPoeContainerLidDL",
                                         G + "ghost/gGiPoeContainerGlassDL", G + "ghost/gGiPoeContainerContentsDL"),
    "gItemIconBottledBugTex": _bottle(G + "insect/gGiBugContainerContentsDL", G + "insect/gGiBugContainerGlassDL"),
    "gItemIconBottledFishTex": _bottle(G + "fish/gGiFishContainerDL"),
    "gItemIconBottledGoldDustTex": _bottle(G + "gold_dust/gGiGoldDustPowderDL", G + "bottle/gGiEmptyBottleGlassDL", G + "bottle/gGiEmptyBottleCorkDL"),
    "gItemIconBottledMushroomTex": _bottle(G + "magicmushroom/gGiMagicMushroomDL", G + "bottle/gGiEmptyBottleGlassDL", G + "bottle/gGiEmptyBottleCorkDL"),
    "gItemIconBottledBlueFireTex": _bottle(G + "bottle/gGiEmptyBottleGlassDL", G + "bottle/gGiEmptyBottleCorkDL"),
    "gItemIconSpringWaterTex": _bottle(G + "bottle/gGiEmptyBottleGlassDL", G + "bottle/gGiEmptyBottleCorkDL"),
    "gItemIconHotSpringWaterTex": _bottle(G + "bottle/gGiEmptyBottleGlassDL", G + "bottle/gGiEmptyBottleCorkDL"),
    "gItemIconBottledDekuPrincessTex": _bottle(G + "bottle/gGiEmptyBottleGlassDL", G + "bottle/gGiEmptyBottleCorkDL"),
    # ---- masks
    "gItemIconDekuMaskTex": _v([G + "nutsmask/gGiDekuMaskDL"], FACE),
    "gItemIconGoronMaskTex": _v([G + "golonmask/gGiGoronMaskDL"], FACE),
    "gItemIconZoraMaskTex": _v([G + "zoramask/gGiZoraMaskDL"], FACE),
    "gItemIconFierceDeityMaskTex": _v([G + "mask03/gGiFierceDeityMaskFaceDL", G + "mask03/gGiFierceDeityMaskHairAndHatDL"], FACE),
    "gItemIconKafeisMaskTex": _v([G + "mask05/gGiKafeiMaskDL"], FACE),
    "gItemIconAllNightMaskTex": _v([G + "mask06/gGiAllNightMaskFaceDL", G + "mask06/gGiAllNightMaskEyesDL"], FACE),
    "gItemIconGaroMaskTex": _v([G + "mask09/gGiGarosMaskCloakDL", G + "mask09/gGiGarosMaskFaceDL"], FACE),
    "gItemIconRomaniMaskTex": _v([G + "mask10/gGiRomaniMaskCapDL", G + "mask10/gGiRomaniMaskNoseEyeDL"], FACE),
    "gItemIconCircusLeaderMaskTex": _v([G + "mask11/gGiCircusLeaderMaskFaceDL", G + "mask11/gGiCircusLeaderMaskEyebrowsDL"], FACE),
    "gItemIconPostmansHatTex": _v([G + "mask12/gGiPostmanHatCapDL", G + "mask12/gGiPostmanHatBunnyLogoDL"], (20, 10, 0)),
    "gItemIconCouplesMaskTex": _v([G + "mask13/gGiCouplesMaskFullDL"], FACE),
    "gItemIconGreatFairyMaskTex": _v([G + "mask14/gGiGreatFairyMaskFaceDL", G + "mask14/gGiGreatFairyMaskLeavesDL"], FACE),
    "gItemIconGibdoMaskTex": _v([G + "mask15/gGiGibdoMaskDL"], FACE),
    "gItemIconDonGeroMaskTex": _v([G + "mask16/gGiDonGeroMaskBodyDL", G + "mask16/gGiDonGeroMaskFaceDL"], FACE),
    "gItemIconKamaroMaskTex": _v([G + "mask17/gGiKamaroMaskDL"], FACE),
    "gItemIconCaptainsHatTex": _v([G + "mask18/gGiCaptainsHatBodyDL", G + "mask18/gGiCaptainsHatFaceDL"], FACE),
    "gItemIconBremenMaskTex": _v([G + "mask20/gGiBremenMaskDL"], FACE),
    "gItemIconBlastMaskTex": _v([G + "mask21/gGiBlastMaskDL"], FACE),
    "gItemIconMaskOfScentsTex": _v([G + "mask22/gGiMaskOfScentsFaceDL", G + "mask22/gGiMaskOfScentsTeethDL"], FACE),
    "gItemIconGiantsMaskTex": _v([G + "mask23/gGiGiantMaskDL"], FACE),
    "gItemIconKeatonMaskTex": _v([G + "ki_tan_mask/gGiKeatonMaskDL", G + "ki_tan_mask/gGiKeatonMaskEyesDL"], FACE),
    "gItemIconBunnyHoodTex": _v([G + "rabit_mask/gGiBunnyHoodDL", G + "rabit_mask/gGiBunnyHoodEyesDL"], FACE),
    "gItemIconStoneMaskTex": _v([G + "stonemask/gGiStoneMaskDL"], FACE),
    "gItemIconMaskOfTruthTex": _v([G + "truth_mask/gGiMaskOfTruthDL", G + "truth_mask/gGiMaskOfTruthAccentsDL"], FACE),
    # ---- equipment
    "gItemIconKokiriSwordTex": _v([G + "sword_1/gGiKokiriSwordBladeHiltDL", G + "sword_1/gGiKokiriSwordGuardDL"], (0, 0, -45)),
    "gItemIconRazorSwordTex": _v([G + "sword_2/gGiRazorSwordDL"], (0, 0, -45)),
    "gItemIconGildedSwordTex": _v([G + "sword_3/gGiGildedSwordDL"], (0, 0, -45)),
    "gItemIconGreatFairysSwordTex": _v([G + "sword_4/gGiGreatFairysSwordBladeDL", G + "sword_4/gGiGreatFairysSwordHiltEmblemDL"], (0, 0, -45)),
    "gItemIconFierceDeitySwordTex": _v([G + "longsword/gGiBiggoronSwordDL"], (0, 0, -45)),
    "gItemIconHerosShieldTex": _v([G + "shield_2/gGiHerosShieldDL", G + "shield_2/gGiHerosShieldEmblemDL"], FACE),
    "gItemIconMirrorShieldTex": _v([G + "shield_3/gGiMirrorShieldDL"], FACE),
    "gItemIconQuiver30Tex": _v([G + "arrowcase/gGiQuiver30InnerColorDL", G + "arrowcase/gGiQuiverInnerDL",
                                G + "arrowcase/gGiQuiver30OuterColorDL", G + "arrowcase/gGiQuiverOuterDL"], (0, 0, -30)),
    "gItemIconQuiver40Tex": _v([G + "arrowcase/gGiQuiver40InnerColorDL", G + "arrowcase/gGiQuiverInnerDL",
                                G + "arrowcase/gGiQuiver40OuterColorDL", G + "arrowcase/gGiQuiverOuterDL"], (0, 0, -30)),
    "gItemIconQuiver50Tex": _v([G + "arrowcase/gGiQuiver50InnerColorDL", G + "arrowcase/gGiQuiverInnerDL",
                                G + "arrowcase/gGiQuiver50OuterColorDL", G + "arrowcase/gGiQuiverOuterDL"], (0, 0, -30)),
    "gItemIconBombBag20Tex": _v([G + "bombpouch/gGiBombBag20BagColorDL", G + "bombpouch/gGiBombBagDL",
                                 G + "bombpouch/gGiBombBag20RingColorDL", G + "bombpouch/gGiBombBagRingDL"]),
    "gItemIconBombBag30Tex": _v([G + "bombpouch/gGiBombBag30BagColorDL", G + "bombpouch/gGiBombBagDL",
                                 G + "bombpouch/gGiBombBag30RingColorDL", G + "bombpouch/gGiBombBagRingDL"]),
    "gItemIconBombBag40Tex": _v([G + "bombpouch/gGiBombBag40BagColorDL", G + "bombpouch/gGiBombBagDL",
                                 G + "bombpouch/gGiBombBag40RingColorDL", G + "bombpouch/gGiBombBagRingDL"]),
    "gItemIconDefaultWalletTex": _v([G + "purse/gGiWalletDL", G + "purse/gGiWalletRupeeInnerDL",
                                     G + "purse/gGiWalletRupeeOuterDL", G + "purse/gGiWalletStringDL"]),
    "gItemIconAdultsWalletTex": _v([G + "purse/gGiAdultWalletColorDL", G + "purse/gGiWalletDL",
                                    G + "purse/gGiAdultWalletRupeeInnerColorDL", G + "purse/gGiWalletRupeeInnerDL",
                                    G + "purse/gGiAdultWalletRupeeOuterColorDL", G + "purse/gGiWalletRupeeOuterDL",
                                    G + "purse/gGiAdultWalletStringColorDL", G + "purse/gGiWalletStringDL"]),
    "gItemIconGiantsWalletTex": _v([G + "purse/gGiGiantsWalletColorDL", G + "purse/gGiWalletDL",
                                    G + "purse/gGiGiantsWalletRupeeInnerColorDL", G + "purse/gGiWalletRupeeInnerDL",
                                    G + "purse/gGiGiantsWalletRupeeOuterColorDL", G + "purse/gGiWalletRupeeOuterDL",
                                    G + "purse/gGiGiantsWalletStringColorDL", G + "purse/gGiWalletStringDL"]),
    "gItemIconHeartPiece1Tex": _v([G + "hearts/gGiHeartPieceDL"], FACE),
    "gItemIconHeartPiece2Tex": _v([G + "hearts/gGiHeartPieceDL"], FACE),
    "gItemIconHeartPiece3Tex": _v([G + "hearts/gGiHeartPieceDL"], FACE),
    # ---- quest status
    "gQuestIconHeartContainerTex": _v([G + "hearts/gGiHeartContainerDL", G + "hearts/gGiHeartBorderDL"], FACE),
    "gQuestIconHeartContainer2Tex": _v([G + "hearts/gGiHeartContainerDL", G + "hearts/gGiHeartBorderDL"], FACE),
    "gQuestIconHeartContainer3Tex": _v([G + "hearts/gGiHeartContainerDL", G + "hearts/gGiHeartBorderDL"], FACE),
    "gQuestIconPieceOfHeartTex": _v([G + "hearts/gGiHeartPieceDL"], FACE),
    "gQuestIconPieceOfHeart2Tex": _v([G + "hearts/gGiHeartPieceDL"], FACE),
    "gQuestIconBossKeyTex": _v([G + "bosskey/gGiBossKeyDL", G + "bosskey/gGiBossKeyGemDL"], (0, 0, -30)),
    "gQuestIconCompassTex": _v([G + "compass/gGiCompassDL", G + "compass/gGiCompassGlassDL"], (0, 50, 0)),
    "gQuestIconDungeonMapTex": _v([G + "map/gGiDungeonMapDL"], (0, 30, 0)),
    "gQuestIconSmallKeyTex": _v([G + "key/gGiSmallKeyDL"], (0, 0, -30)),
    "gQuestIconSmallMagicJarTex": _v([G + "magicpot/gGiMagicJarSmallDL"]),
    "gQuestIconBigMagicJarTex": _v([G + "magicpot/gGiMagicJarLargeDL"]),
    "gQuestIconGoldSkulltulaTex": _v([G + "sutaru/gGiSkulltulaTokenDL"], FACE),
    "gQuestIconGoldSkulltula2Tex": _v([G + "sutaru/gGiSkulltulaTokenDL"], FACE),
}
